Exam 2 Olha Nemensha
viktor-beet-root/exam-js pull request #5
Opened 2021-02-18 19:47 UTC by olhanemensha

2021-02-21 17:18 UTC, viktor-beet-root requested changes

2021-02-21 17:18 UTC, viktor-beet-root commented on nemensha_olha/build/css/style.css
> +/*# sourceMappingURL=data:application/json;charset=utf8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIl90aXBvZ3JhZnkuc2NzcyIsIl92YXJzLnNjc3MiLCJfbWl4aW4uc2NzcyIsIl9mb250cy5zY3NzIiwiX2dyaWQuc2NzcyIsInN0eWxl
соурсмапов не должно быть при сдаче

2021-02-21 17:18 UTC, viktor-beet-root commented on nemensha_olha/src/css/_btn.scss
> +}
что забыла

2021-02-21 17:18 UTC, viktor-beet-root commented on nemensha_olha/src/css/_burgermenu.scss
> +}
проверь все файлы

2021-02-21 17:18 UTC, viktor-beet-root commented on nemensha_olha/src/index.html
> +    <link rel="stylesheet" href="./css/style.css">
фавиконка?

2021-02-21 17:18 UTC, viktor-beet-root commented on nemensha_olha/src/index.html
> +        function initMap() {
js тут не должно быть все в отдельном файле

2021-02-21 17:18 UTC, viktor-beet-root commented on nemensha_olha/src/js/lib/sidebar.js
> +    scrollFunction()
вызов этой функции должне быть асинхронным
и если смысл ее вызывать если она уже отработала?

2021-02-28 06:59 UTC, olhanemensha commented on nemensha_olha/src/css/_btn.scss
> +}
не поняла что надо исправить

2021-02-28 06:59 UTC, olhanemensha commented on nemensha_olha/src/css/_burgermenu.scss
> +}
и тут тоже

2021-03-01 20:03 UTC, merged